### ISSUE TITLE
Installing fresh solidus and solidus_reviews, rails g solidus_reviews:install fails

### ISSUE THREAD

**Issue by mbjornson** [solidusio-contrib/solidus_reviews#100]
# Gemfile
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'
gem 'pg'
gem 'puma', '~> 4.1'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 4.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem 'solidus'
gem 'solidus_reviews', github: 'solidusio-contrib/solidus_reviews'
# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

bundle added the gem, but running 'be rails solidus_reviews:install' fails, with the following error

`
/Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- deface (LoadError)
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/solidus_reviews-dec46eae286f/lib/solidus_reviews.rb:5:in `<main>'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:69:in `each'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:58:in `each'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:58:in `require'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler.rb:174:in `require'
	from /Users/matt/code/solidus-commerce/config/application.rb:7:in `<top (required)>'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /Users/matt/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from -e:1:in `<main>'
`

**Comment by mbjornson** [comment]
`
#added to
gem 'deface', github: 'spree/deface'
gem 'solidus_reviews', github: 'solidusio-contrib/solidus_reviews'
`
ran bundle and it worked.
