### ISSUE TITLE
Uninitialized constant error (Spree::ProductsController)

### ISSUE THREAD

**Issue by Buvanesh-P** [solidusio-contrib/solidus_reviews#120]
`products_controller_decorator` searching for `Spree::ProductsController` which not exist

**Steps to reproduce**

1. Add the gem `gem 'solidus_reviews'`
2. `rails generate solidus_reviews:install`

`/var/lib/gems/3.0.0/gems/solidus_reviews-1.7.0/app/decorators/controllers/solidus_reviews/spree/products_controller_decorator.rb:12:in `<module:ProductsControllerDecorator>': uninitialized constant Spree::ProductsController (NameError)
        from /var/lib/gems/3.0.0/gems/solidus_reviews-1.7.0/app/decorators/controllers/solidus_reviews/spree/products_controller_decorator.rb:5:in `<module:Spree>'
        from /var/lib/gems/3.0.0/gems/solidus_reviews-1.7.0/app/decorators/controllers/solidus_reviews/spree/products_controller_decorator.rb:4:in `<module:SolidusReviews>'
        from /var/lib/gems/3.0.0/gems/solidus_reviews-1.7.0/app/decorators/controllers/solidus_reviews/spree/products_controller_decorator.rb:3:in `<main>'
        from /var/lib/gems/3.0.0/g..............................`
        
        
![image](https://github.com/user-attachments/assets/58ebddc1-cf84-41c9-a6d2-853ead5c8f00)

**Comment by jarednorman** [comment]
My guess is that you've installed this extension on a store that's using Solidus Starter Frontend, but this extension hasn't been updated to support it.

**Comment by fthobe** [comment]
@jarednorman what would be the most elegant way to solve this? We could spare some time for that.

**Comment by jarednorman** [comment]
The project would need to be reviewed (pun intended) to determine which ways it assumes you're using the original solidus_frontend instead of solidus_starter_frontend.

My preference would be that you then update the gem to work with the starter frontend (and possibly the new admin too) and then bump it to a new major version.

It should be possible to craft this extension such that it can be used with either frontend, but it wouldn't be directly compatible with existing installations without some changes.

**Comment by fthobe** [comment]
We don't want to put hands into the work in progress you are doing with the Admin backend, if we take care of the front-end aspects, could you people handle the backend?

**Comment by fthobe** [comment]
@Buvanesh-P Did anybody on your side fix this?
> `products_controller_decorator` searching for `Spree::ProductsController` which not exist
> 
> **Steps to reproduce**
> 
> 1. Add the gem `gem 'solidus_reviews'`
> 2. `rails generate solidus_reviews:install`

**Comment by fthobe** [comment]
> > `products_controller_decorator` searching for `Spree::ProductsController` which not exist
> > **Steps to reproduce**
> > 
> > 1. Add the gem `gem 'solidus_reviews'`
> > 2. `rails generate solidus_reviews:install`

@kennyadsl should the old front-end be globally dropped or is it currently something you support?

**Comment by jarednorman** [comment]
I don't think drop it is a good idea, given supporting both isn't all that much work.

**Comment by fthobe** [comment]
@jarednorman @kennyadsl please align on desired level of support.

**Comment by kennyadsl** [comment]
I'm ok with Jared proposed. It's the same thing we did for Subscriptions, which I pointed you to in Slack.

**Comment by fthobe** [comment]
> It should be possible to craft this extension such that it can be used with either frontend, but it wouldn't be directly compatible with existing installations without some changes.

@kennyadsl is the above ok for you? For us a review that works with the old solidus frontend is beyond test scope and I wouldn't like to commit something that we haven't tested (with humans) end to end. I just do not have the same amount of faith in automated testing.

**Comment by kennyadsl** [comment]
What do you suggest in this case?

**Comment by fthobe** [comment]
To be fully honest three things: 

- old frontend is deprecated by docs, so let's deprecate it, new versions for gems aligned with the solidus numbering scheme so let's bump extensions from whatever version to 4.4. I feel having less stuff reliably running is better than more stuff cramped into not working environments and outdated front ends, as you said regarding solidus 5 the ecosystem needs to work first and right now I have the feeling that instead of keeping a pace that works for the entire ecosystem what should be major releases are made minor releases while abandoning the eco system in non working state
- dropping the old front end allows a reduction of manual test cases to a minimum by having to test only against one front-end, one backend
- add manual testing by spinning up a public staging system for nightly main and beta (I feel that would be a good way to use community funds) and write a manual test protocol, I think there's only so far automated testing can get you as stuff not considered in development will not be considered in circleci and the effort is definitely less stressful than forcing out overnight updates and I wouldn't want to have to mantain them on two frontends concurrently
- pay some dude on upwork 50 bucks a month to test against the protocol on staging a couple of times a month (also community funded) 

I know the for example that the new promotion system was a monster task but I have the feeling with a little bit more manual testing a lot of stuff would have been caught earlier and to do manual testing against both frontends seems a nightmare to me, let's not pray to a dead cow. But that's my cup of tea and I wouldn't die on that hill (different than meta data which is something I deem immensely important for the eco system), but I feel that would be a better approach.

**Comment by jarednorman** [comment]
I don't have time to dive into everything here right now, but I wanted to comment on a couple of things.

> old frontend is deprecated by docs, so let's deprecate it

Most existing stores use the legacy frontend and there isn't a practical upgrade path, so we need to maintain support for it.

> new versions for gems aligned with the solidus numbering scheme so let's bump extensions from whatever version to 4.4

No. This is a terrible idea for a number of reasons, including that we would have to ship new versions of every supported gem every time we release a new Solidus version.

**Comment by fthobe** [comment]
> No. This is a terrible idea for a number of reasons, including that we would have to ship new versions of every supported gem every time we release a new Solidus version.

ok

> old frontend is deprecated by docs, so let's deprecate it

Is this up for discussion, how far do we want to go here?

**Comment by jarednorman** [comment]
It's not hard to support both the starter and legacy frontend. We can have new major versions of extensions that require users update a couple of things if they are using the legacy frontend. Typically extensions that expect the starter frontend make _fewer_ assumptions about the codebase they are being added to than those that depend on the legacy frontend, or that should be true.

**Comment by fthobe** [comment]
@jarednorman One of our first PRs was a complete rewrite of reviews including support for both Frontends and passing tests. 

Being one of our first PRs the commit structure was not to everybody's liking, it's up to you if you: 
- wait till we have the time to break it down into smaller commits
- review it like it is
- decide where the extension should be placed (core / contrib). 

Done it's done. 
https://github.com/solidusio-contrib/solidus_reviews/pull/131

**Comment by jarednorman** [comment]
If this is an extensive rewrite, then I propose that you release it as new extension and we go from there.
