### ISSUE TITLE
Can't modify frozen String error when trying to open Admin

### ISSUE THREAD

**Issue by juan267** [solidusio-contrib/solidus_reviews#58]
After adding the gem Im getting the following error:

```
Deface: 1 overrides found for 'spree/admin/shared/_product_sub_menu'
Deface: 'reviews_admin_tab' matched 1 times with '[data-hook='admin_product_sub_tabs']'
Deface: [WARNING] No :original defined for 'reviews_admin_tab', you should change its definition to include:
 :original => 'd1a70da8f31da0a082c6c5333d9837dcaca65c65'
  Rendered vendor/bundle/gems/solidus_backend-2.7.2/app/views/spree/admin/shared/_tabs.html.erb (15.3ms)
  Rendered vendor/bundle/gems/solidus_backend-2.7.2/app/views/spree/admin/shared/_menu.html.erb (18.0ms)
  Rendered vendor/bundle/gems/solidus_backend-2.7.2/app/views/spree/admin/shared/_navigation.html.erb (25.6ms)
Completed 500 Internal Server Error in 2956ms (ActiveRecord: 68.1ms)



ActionView::Template::Error (can't modify frozen String):
     8:         url: menu_item.url.is_a?(Symbol) ? spree.public_send(menu_item.url) : menu_item.url
     9:       ) do
    10:     %>
    11:       <%- render partial: menu_item.partial if menu_item.partial %>
    12:     <%- end %>
    13:   <% end %>
    14: <% end %>

vendor/bundle/gems/deface-1.3.2/lib/deface/parser.rb:93:in `force_encoding'
vendor/bundle/gems/deface-1.3.2/lib/deface/parser.rb:93:in `convert'
vendor/bundle/gems/deface-1.3.2/lib/deface/override.rb:154:in `source_element'
```

Rails: 5.1.6.2
ruby: 2.6.3p62

I also try it with   ruby `2.5.5` and the same error occurred.

**Comment by juan267** [comment]
The problem appear to be the pragma comment. Maybe deface it's mutating string when `insert_bottom` is used?

**Comment by aldesantis** [comment]
@juan267 this is a problem with older versions of Deface. Please try to update to > 1.5 and let me know if the issue persists!
